[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableStaticServing = true

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
caching = true
displayEnabled = true
