# Database configurations
[database]
host = "localhost"
port = 5432
username = "your_username"
password = "your_password"
database = "lifeline_air"

# API Keys
[api_keys]
weather_api_key = "your_weather_api_key"
maps_api_key = "your_maps_api_key"
notification_api_key = "your_notification_key"

# Authentication
[auth]
secret_key = "your_secret_key_here"
session_timeout = 1800

# External Services
[services]
redis_url = "redis://localhost:6379"
backup_storage = "your_backup_storage_url"
